source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

target 'ForSwift' do

pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'SnapKitExtend'
pod 'HandyJSON'
pod 'Moya'
#  pod 'Result'
#  pod 'Kingfisher'
pod 'Then'
pod 'Reusable'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'URLNavigator'
pod 'CHTCollectionViewWaterfallLayout'
pod 'JFPopup'
#  pod 'JXSegmentedView'
pod 'Onboard'
pod 'FSPagerView'
pod 'BSText'
pod 'DateToolsSwift'

pod 'SKPhotoBrowser' 
pod 'ZLPhotoBrowser'
pod 'JFHeroBrowser'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Needed for building for simulator on M1 Macs
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
        # 开启 RxSwift.Resources.total
        if target.name == 'RxSwift'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                end
            end
        end
    end
end

